version: '2.3'
networks:
  default:
    driver: bridge
    ipam: 
      config: 
        - subnet: '172.31.0.0/16'

services:
  age_estimate_public:
    image: nvcr.io/nvidia/pytorch:21.06-py3
    runtime: nvidia
    build: .
    volumes:
        - ./src:/workspace/estimation_src
        - ./dataset:/workspace/dataset
    ports:
      - "6000:6006"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    tty: True

